# Generated by Django 4.2.18 on 2025-01-24 14:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StapleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('measurement_unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Pieces'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('can', 'Can')], max_length=50)),
                ('category', models.CharField(choices=[('bakery', 'Bread & Bakery'), ('baking', 'Baking'), ('baby', 'Baby Items'), ('beverages', 'Beverages'), ('canned', 'Canned Goods'), ('condiments', 'Condiments & Spices'), ('dairy', 'Dairy'), ('deli', 'Deli'), ('frozen', 'Frozen Foods'), ('fruits', 'Fruits'), ('health', 'Health Care'), ('household', 'Household & Cleaning Supplies'), ('meat', 'Meat'), ('pasta', 'Pasta, Rice & Cereal'), ('personal', 'Personal Care'), ('pet', 'Pet Care'), ('produce', 'Vegetables'), ('seafood', 'Fish & Seafood'), ('snacks', 'Snacks')], max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staple_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
